# Generated by Django 5.1.5 on 2025-09-29 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d0d4ea00-ed60-4f65-9a8d-6f280eed0f90')),
        ),
    ]
