# Generated by Django 5.1.5 on 2025-04-08 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='attributes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('013365c4-baff-4a13-861a-2b2b0422c964')),
        ),
    ]
