# Generated by Django 5.1.5 on 2025-09-29 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlistitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a33ca935-db79-4a66-afcf-87ae2211d6cc')),
        ),
    ]
