# Generated by Django 5.1.5 on 2025-09-29 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlistitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e8babc39-bd2a-40d6-90e4-74cca9464ba5')),
        ),
    ]
