version: '2.2'
services:
  kibana:
    depends_on:
      - es01
    image: public.ecr.aws/elastic/kibana:7.17.10
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_URL: http://es01:9200
    networks:
      - elastic

  es01:
    image: public.ecr.aws/elastic/elasticsearch:7.17.10
    container_name: es01
    ports:
      - 9200:9200
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/var/lib/elasticsearch
    networks:
      - elastic

volumes:
  esdata01:
    driver: local

networks:
  elastic:
    driver: bridge