# Generated by Django 4.2.5 on 2024-08-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carduser',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
