# Generated by Django 4.2.5 on 2024-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_carduser_is_selected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-expiration_year']},
        ),
        migrations.AlterModelOptions(
            name='carduser',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='carduser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
