# Generated by Django 4.2.5 on 2024-09-21 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_alter_card_options_alter_carduser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(through='billing.CardUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
