# Generated by Django 4.2.5 on 2024-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_card_options_card_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('card.active', 'Active'), ('card.deactivated', 'Deactivated'), ('card.deleted', 'Deleted'), ('card.expired', 'Expired')], default='card.active', max_length=40),
        ),
    ]
