# Generated by Django 5.1.2 on 2024-10-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(db_default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_selected',
            field=models.BooleanField(db_default=False),
        ),
    ]
