# Generated by Django 4.2.5 on 2023-11-28 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=40)),
                ('total_price', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_shipped', models.BooleanField(default=False)),
                ('date_shipped', models.DateTimeField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(default=None, max_length=120)),
                ('manufacturer', models.CharField(default=None, max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_shipped', False)), fields=['id'], name='unshipped_orders'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_shipped', False)), fields=['buyer_id'], name='order_buyer_id'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_shipped', False)), fields=['seller_id'], name='order_seller_id'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('is_shipped', False)), fields=('buyer_id', 'is_shipped'), name='limit_pending_orders'),
        ),
    ]
