# Generated by Django 4.2.5 on 2023-11-30 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order_supplier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b45ec860-3a96-4b37-ab27-12250671762b')),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8f5e2c19-5038-443b-a940-c1f1a8ed63f8')),
        ),
    ]
