# Generated by Django 4.2.5 on 2023-11-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_shipped_order_unshipped_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shipped',
            field=models.DateTimeField(null=True),
        ),
    ]
