# Generated by Django 4.2.5 on 2023-12-04 07:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_uuid_alter_orderitem_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='s_order_item_product_name_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('89d5b503-d2a0-473a-b21f-84332d194e07')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8a00afe3-708a-48b0-97d3-a9e9cb12e4c2')),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('product_name', 'manufacturer', config='english'), name='s_order_item_product_name_idx'),
        ),
    ]
