# Generated by Django 4.2.5 on 2023-11-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_date_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
    ]
