# Generated by Django 4.2.5 on 2023-12-04 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c42fcd12-d079-410c-a702-449ff4dfac09')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('16c0984a-758b-4c2d-9f46-9ebcee93fa04')),
        ),
    ]
