# Generated by Django 4.2.5 on 2023-12-18 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d533cb52-4d3f-4131-9c09-b32353f5145c')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e026650f-2b20-4806-9fdd-7c3d1707b4bf')),
        ),
    ]
