# Generated by Django 4.2.5 on 2023-12-29 10:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='s_order_item_product_name_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5af846a1-47ff-458e-9ff1-101941cf8a36')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('69cc9732-1636-4464-956a-587f504def33')),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('product_name', 'sku', 'manufacturer', config='english'), name='s_order_item_product_name_idx'),
        ),
    ]
