# Generated by Django 4.2.5 on 2024-01-02 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderitem_s_order_item_product_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6219366a-b276-4918-bb12-98785e92e166')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e7a9cf7e-b5b4-4009-8846-c96c77c7ce9d')),
        ),
    ]
