# Generated by Django 4.2.5 on 2023-12-04 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('79b4f53a-6a6a-49d8-8744-5ac7fbc537e5')),
        ),
    ]
