# Generated by Django 4.2.5 on 2023-12-04 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b549ce95-7bc8-4980-b12d-6ae35122812c')),
        ),
    ]
