# Generated by Django 4.2.5 on 2023-12-18 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aff7d7c7-22f6-4681-bbe5-d777af2735ec')),
        ),
    ]
