# Generated by Django 4.2.5 on 2024-01-02 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('742b6a39-d810-4a7e-ad7e-b04f2f17b5df')),
        ),
    ]
