# Generated by Django 4.2.5 on 2023-12-04 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('65e77a47-04df-42ab-aebd-f7fa7afd8d48')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('35a22bf5-3415-4c11-ba20-c8b750aeaf90')),
        ),
    ]
