# Generated by Django 4.2.5 on 2024-01-02 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e55679b9-e29f-456e-9bf4-d06a45aaa48e')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9aece98d-3dd3-438a-a90c-ac42372fabcd')),
        ),
    ]
