# Generated by Django 5.1.2 on 2024-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_user_email_comment_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
