# Generated by Django 4.2.5 on 2024-05-23 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_uuid_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d4167cba-95b0-4d34-9386-75ab1635b85a')),
        ),
    ]
