# Generated by Django 4.2.5 on 2024-05-23 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('450f13f8-2bc3-406e-b988-1eee9d73bb8d')),
        ),
    ]
