# Generated by Django 4.2.5 on 2024-05-23 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('02dd9ac0-95a1-4c75-b5e0-74004ea4b506')),
        ),
    ]
