# Generated by Django 4.2.5 on 2024-05-24 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6e51260b-12cc-4190-936c-7b6b1c18452e')),
        ),
    ]
