# Generated by Django 4.2.5 on 2024-06-01 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8db1e14d-df98-4945-bced-3ffb1198c841')),
        ),
    ]
