# Generated by Django 4.2.5 on 2024-06-05 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('de76df40-f00d-47b9-a6c7-80a50712ccab')),
        ),
    ]
