# Generated by Django 4.2.5 on 2024-06-05 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ad432da9-c1c7-40f0-abfe-ccb4db84f0fc')),
        ),
    ]
