# Generated by Django 4.2.5 on 2024-06-28 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('468dc7b6-1a7f-4baa-8edd-1904cb0f0695')),
        ),
    ]
