# Generated by Django 4.2.5 on 2024-07-01 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3cfcb316-f1ee-4c29-b4b5-4294b384ff81')),
        ),
    ]
