# Generated by Django 4.2.5 on 2024-07-03 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('50bb5662-cd9d-49b4-aea4-b11666ee71e3')),
        ),
    ]
