# Generated by Django 4.2.5 on 2024-07-03 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2ad937ef-9a54-44ff-b41e-e7092631b9d0')),
        ),
    ]
