# Generated by Django 4.2.5 on 2024-07-03 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('30154009-8a4c-4234-9152-5ff95b52bf2e')),
        ),
    ]
