# Generated by Django 4.2.5 on 2024-08-21 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2fa39d76-6015-4d90-9410-2f963142c226')),
        ),
    ]
