# Generated by Django 4.2.5 on 2024-08-22 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d8e5c170-270e-4f1b-876a-5070711271a4')),
        ),
    ]
