# Generated by Django 4.2.5 on 2024-09-02 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7f1239ab-623d-4f16-ab7b-e7f8af377c19')),
        ),
    ]
