# Generated by Django 4.2.5 on 2024-09-21 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7ac7a825-9c27-4e85-baec-f5d6cd5cb665')),
        ),
    ]
