# Generated by Django 4.2.5 on 2024-09-21 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('00414825-7f5d-4fcc-ad70-72b5da81da38')),
        ),
    ]
