# Generated by Django 4.2.5 on 2024-09-21 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0aad68ab-3359-41f7-b201-12e13e920e49')),
        ),
    ]
