# Generated by Django 5.1.2 on 2024-10-10 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cf278a23-b5b4-4e5b-a7a9-2bf7eb0915bb')),
        ),
    ]
