# Generated by Django 5.1.2 on 2024-10-10 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7e39607e-73f1-43ca-8b8d-a37d0f671d93')),
        ),
    ]
