# Generated by Django 5.1.2 on 2024-10-10 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2971cb07-4b86-4e59-ab3d-b2b35f6eeb7d')),
        ),
    ]
