# Generated by Django 5.1.2 on 2024-10-10 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ee80196b-173c-4a94-a7bc-8e2e44418b8c')),
        ),
    ]
