# Generated by Django 5.1.2 on 2024-10-10 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d59e9c21-0a31-4f45-964c-ae1ffd473d5e')),
        ),
    ]
