# Generated by Django 5.1.2 on 2024-10-10 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('07ec4624-5090-4a6d-9bf7-2671dad315b4')),
        ),
    ]
