# Generated by Django 5.1.2 on 2024-10-10 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b7c6b34d-29d8-4974-8170-0d9fc6f28ea6')),
        ),
    ]
