# Generated by Django 5.1.2 on 2024-10-10 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0133bfc2-b84b-4e02-a40d-082c64ed9785')),
        ),
    ]
