# Generated by Django 5.1.2 on 2024-10-21 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0042_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('01658233-c207-4bf2-8123-b2ece2ff8757')),
        ),
    ]
