# Generated by Django 5.1.2 on 2024-10-21 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0043_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a46e4dab-927c-4f3f-ac6b-84a83673e79d')),
        ),
    ]
