# Generated by Django 5.1.2 on 2024-10-22 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0046_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a9fad088-7865-49e1-9b06-f07644be9755')),
        ),
    ]
