# Generated by Django 5.1.2 on 2024-10-23 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0048_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6cf090cd-8440-4861-8d6b-ec8c29b21a3d')),
        ),
    ]
