# Generated by Django 5.1.2 on 2024-10-23 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0049_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5b54ee45-9a62-4e88-971c-2d00e081fb48')),
        ),
    ]
