# Generated by Django 5.1.2 on 2024-10-24 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0050_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3daa30de-dfed-46e6-a5ee-ea93ba95ac65')),
        ),
    ]
