# Generated by Django 5.1.2 on 2024-10-30 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0052_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6af0c701-0a80-4a0f-9f3b-6d2b20bff8b8')),
        ),
    ]
