# Generated by Django 5.1.2 on 2025-01-13 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0055_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7279e3ab-d71c-494e-882a-14379b8edb6b')),
        ),
    ]
