# Generated by Django 5.1.2 on 2025-01-13 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0056_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('57fbc10f-8408-451d-8095-2c9349808ae0')),
        ),
    ]
