# Generated by Django 5.1.2 on 2025-01-13 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0057_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('59d624ef-6b51-4ab1-a2f3-522c29359b82')),
        ),
    ]
