# Generated by Django 5.1.5 on 2025-02-07 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0058_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fced2e5d-75b4-4c87-a521-4da0c0f3998f')),
        ),
    ]
