# Generated by Django 5.1.5 on 2025-04-08 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0060_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('af7aa0d7-fdd2-47a8-9967-fb6013558023')),
        ),
    ]
