# Generated by Django 5.1.5 on 2025-04-08 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0061_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cb215e5c-0795-4afa-8987-9d3995bdb5d3')),
        ),
    ]
