# Generated by Django 5.1.5 on 2025-04-10 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0062_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('97f75227-e51a-495d-ae0c-b2983c6016d1')),
        ),
    ]
