# Generated by Django 5.1.5 on 2025-09-29 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0063_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4fa407e2-88f2-46d9-a73e-8fb5dce60324')),
        ),
    ]
