# Generated by Django 5.1.5 on 2025-09-29 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0064_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ced8d025-abe5-4f5d-afa4-5151f3085494')),
        ),
    ]
