# Generated by Django 5.1.5 on 2025-09-29 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0067_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b84d0bae-8532-42ac-a4ff-2e2f76c5bfc3')),
        ),
    ]
