# Generated by Django 5.1.5 on 2025-09-29 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0068_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ad5d9355-122e-4155-933c-420bcd8bab8f')),
        ),
    ]
