# Generated by Django 5.1.5 on 2025-09-29 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0069_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f47dfb67-b074-4569-8812-0b6b328b5b37')),
        ),
    ]
