# Generated by Django 4.2.5 on 2024-07-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='button_css_class',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
