# Generated by Django 4.2.5 on 2024-09-23 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socials', '0002_social_button_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='users',
            field=models.ManyToManyField(through='socials.SocialUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
