# Generated by Django 5.1.5 on 2025-09-29 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('alt', models.TextField(null=True)),
                ('object_id', models.PositiveSmallIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='posts/default.jpg', upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_profile_image', models.BooleanField(default=False)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('image_type', models.CharField(max_length=20, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_profile_image'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_profile_image', True), ('content_type', 17)), fields=('object_id', 'is_profile_image', 'content_type'), name='one_user_profile_image')],
            },
        ),
    ]
