# Generated by Django 4.2.5 on 2024-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='user',
            new_name='uploaded_by',
        ),
        migrations.AddField(
            model_name='images',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to='images/'),
        ),
    ]
