# Generated by Django 4.2.5 on 2024-07-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_images_is_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='images',
            name='one_user_profile_image',
        ),
        migrations.AddConstraint(
            model_name='images',
            constraint=models.UniqueConstraint(condition=models.Q(('is_profile_image', True), ('content_type', 17)), fields=('object_id', 'is_profile_image', 'content_type'), name='one_user_profile_image'),
        ),
    ]
