# Generated by Django 4.2.5 on 2024-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_images_one_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
