# Generated by Django 4.2.5 on 2023-11-27 11:55

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_remove_user_user_type_delete_usertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': [django.db.models.functions.text.Lower('username')]},
        ),
    ]
