# Generated by Django 4.2.5 on 2023-11-30 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f34ab8e8-443f-40f4-9c76-e093f94b812b')),
        ),
    ]
