# Generated by Django 4.2.5 on 2023-11-30 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f4a0e7a5-a6b1-40f6-9ea2-e10876dc74ea')),
        ),
    ]
