# Generated by Django 4.2.5 on 2023-12-04 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0014_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1e664185-6f37-41a1-a363-932d0d8766b1')),
        ),
    ]
