# Generated by Django 4.2.5 on 2023-12-04 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0016_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('46a00ed6-e3e5-4e4e-a36a-a3769fcb07e7')),
        ),
    ]
