# Generated by Django 4.2.5 on 2023-12-18 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0019_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c14ba31c-6df1-4f0b-ab0e-b8326a406965')),
        ),
    ]
