# Generated by Django 4.2.5 on 2024-01-02 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0023_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1a4273a6-d790-4600-8594-e8cd2dd5733b')),
        ),
    ]
