# Generated by Django 4.2.5 on 2024-05-23 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0025_alter_user_email_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('abc6b2d6-4a9e-45b6-ac19-d331b8738f5a')),
        ),
    ]
