# Generated by Django 4.2.5 on 2024-05-23 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0027_user_is_verified_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bb3a4493-eb52-4537-964f-c548dbc1c131')),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default=None, max_length=120)),
                ('city', models.CharField(default=None, max_length=120)),
                ('address', models.CharField(default=None, max_length=120)),
                ('zip', models.CharField(default=None, max_length=20)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
