# Generated by Django 4.2.5 on 2024-05-24 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0029_remove_userdetails_id_alter_user_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6afc1623-b543-4bc7-b222-f43fe1bdf07f')),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='zip',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
