# Generated by Django 4.2.5 on 2024-05-24 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0032_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('user.unverified', 'Unverified'), ('user.active', 'Active'), ('user.deactivated', 'Deactivated'), ('user.deleted', 'Deleted')], default='user.unverified', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d8480d78-a9c8-40b6-b205-79a3a719ce2f')),
        ),
    ]
