# Generated by Django 4.2.5 on 2024-06-05 12:55

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0006_delete_aggregateevent'),
        ('custom_auth', '0035_alter_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email.address')),
                ('uuid', models.UUIDField(default=uuid.UUID('a9720847-fdac-4673-a995-273645c92b7d'))),
                ('bio', models.TextField(default=None, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('user.unverified', 'Unverified'), ('user.active', 'Active'), ('user.deactivated', 'Deactivated'), ('user.deleted', 'Deleted')], default='user.unverified', max_length=40)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a9720847-fdac-4673-a995-273645c92b7d')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "custom_auth_userevent" ("bio", "created_date", "cv", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "is_verified", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_date", "uploaded_at", "username", "uuid") VALUES (NEW."bio", NEW."created_date", NEW."cv", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."is_verified", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."updated_date", NEW."uploaded_at", NEW."username", NEW."uuid"); RETURN NULL;', hash='d9671248556cdb73a75ed9270ec569950a4f747e', operation='INSERT', pgid='pgtrigger_insert_insert_3f24c', table='custom_auth_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "custom_auth_userevent" ("bio", "created_date", "cv", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "is_verified", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_date", "uploaded_at", "username", "uuid") VALUES (NEW."bio", NEW."created_date", NEW."cv", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."is_verified", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."updated_date", NEW."uploaded_at", NEW."username", NEW."uuid"); RETURN NULL;', hash='f374ef0fcf6ced96632f2884eb079cdb487229ae', operation='UPDATE', pgid='pgtrigger_update_update_a6368', table='custom_auth_user', when='AFTER')),
        ),
        migrations.AddField(
            model_name='userevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
