# Generated by Django 4.2.5 on 2024-06-05 13:08

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0036_userevent_alter_user_uuid_user_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1c06c59d-9bb1-4fe3-9272-7f669cdb0a6a')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1c06c59d-9bb1-4fe3-9272-7f669cdb0a6a')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='ea66d6f754bcf9ce8c04df7b9d4121bf592f1df4', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_28b87', table='custom_auth_userevent', when='BEFORE')),
        ),
    ]
