# Generated by Django 4.2.5 on 2024-06-28 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0039_alter_user_uuid_alter_userevent_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ebd6cc2d-7310-43cb-9f8f-72c56a85ebea')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ebd6cc2d-7310-43cb-9f8f-72c56a85ebea')),
        ),
    ]
