# Generated by Django 4.2.5 on 2024-07-01 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0040_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='country',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('467a912b-cbce-4c46-b09f-59825c2f9411')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('467a912b-cbce-4c46-b09f-59825c2f9411')),
        ),
    ]
