# Generated by Django 4.2.5 on 2024-07-03 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0042_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3eb91701-c6bb-454b-87d9-92af14199d5b')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3eb91701-c6bb-454b-87d9-92af14199d5b')),
        ),
    ]
