# Generated by Django 4.2.5 on 2024-08-21 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0047_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a15fe365-9ecc-4df8-af9e-791e73f667b4')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a15fe365-9ecc-4df8-af9e-791e73f667b4')),
        ),
    ]
