# Generated by Django 4.2.5 on 2024-09-21 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0050_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3329c97c-8319-48e8-baff-12e69c091910')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3329c97c-8319-48e8-baff-12e69c091910')),
        ),
    ]
