# Generated by Django 4.2.5 on 2024-09-21 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0052_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('985a7ebc-96f3-44ce-99ba-b8bbd46f4f40')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('985a7ebc-96f3-44ce-99ba-b8bbd46f4f40')),
        ),
    ]
