# Generated by Django 4.2.5 on 2024-09-21 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0053_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('045c6e7f-3ad7-4d70-b345-7a27dd92c077')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('045c6e7f-3ad7-4d70-b345-7a27dd92c077')),
        ),
    ]
