# Generated by Django 5.1.2 on 2024-10-10 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0057_alter_user_is_verified_alter_user_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('015effc7-4ca0-4270-89e4-e44ad0209e4e')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('015effc7-4ca0-4270-89e4-e44ad0209e4e')),
        ),
    ]
