# Generated by Django 5.1.2 on 2024-10-10 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0059_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('52ee6bfd-f685-425d-ae0b-9e3e3749b7a2')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('52ee6bfd-f685-425d-ae0b-9e3e3749b7a2')),
        ),
    ]
