# Generated by Django 5.1.2 on 2024-10-10 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0060_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e4732c9-ebab-4acb-a24c-af5ffaee0aff')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e4732c9-ebab-4acb-a24c-af5ffaee0aff')),
        ),
    ]
