# Generated by Django 5.1.2 on 2024-10-10 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0061_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('585b7ebb-1bdf-4051-8548-9f04f70770e6')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('585b7ebb-1bdf-4051-8548-9f04f70770e6')),
        ),
    ]
