# Generated by Django 5.1.2 on 2024-10-10 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0062_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7e3d8626-016a-459c-b53f-0a7faffb263a')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7e3d8626-016a-459c-b53f-0a7faffb263a')),
        ),
    ]
