# Generated by Django 5.1.2 on 2024-10-10 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0063_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('user.unverified', 'Unverified'), ('user.active', 'Active'), ('user.deactivated', 'Deactivated'), ('user.deleted', 'Deleted')], db_default='user.unverified', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('70e30c52-6c8d-4c54-9baa-e926171c6341')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='status',
            field=models.CharField(choices=[('user.unverified', 'Unverified'), ('user.active', 'Active'), ('user.deactivated', 'Deactivated'), ('user.deleted', 'Deleted')], db_default='user.unverified', max_length=40),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('70e30c52-6c8d-4c54-9baa-e926171c6341')),
        ),
    ]
