# Generated by Django 5.1.2 on 2024-10-10 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0064_alter_user_status_alter_user_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc9d603e-8a7e-4b72-b16d-abff262c84bd')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc9d603e-8a7e-4b72-b16d-abff262c84bd')),
        ),
    ]
