# Generated by Django 5.1.2 on 2024-10-21 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0066_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('268d32d3-e4cf-4248-8cb8-f72dfa18dac0')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('268d32d3-e4cf-4248-8cb8-f72dfa18dac0')),
        ),
    ]
