# Generated by Django 5.1.2 on 2024-10-22 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0069_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b6c74bb5-a076-43f5-bdd4-be6cedb6648c')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b6c74bb5-a076-43f5-bdd4-be6cedb6648c')),
        ),
    ]
