# Generated by Django 5.1.2 on 2024-10-22 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0070_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2cc8d376-6526-4f52-a88d-9c8d3c8de7fc')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2cc8d376-6526-4f52-a88d-9c8d3c8de7fc')),
        ),
    ]
