# Generated by Django 5.1.2 on 2024-10-23 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0071_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('376898ac-7c3b-4f1e-bba2-a658ce526d54')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('376898ac-7c3b-4f1e-bba2-a658ce526d54')),
        ),
    ]
