# Generated by Django 5.1.2 on 2024-10-23 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0072_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ca746f61-f7f6-4aec-81f2-a5123da60506')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ca746f61-f7f6-4aec-81f2-a5123da60506')),
        ),
    ]
