# Generated by Django 5.1.2 on 2024-11-19 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0076_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ddd2986b-7b7a-4b43-81fc-7eee527dc1a5')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ddd2986b-7b7a-4b43-81fc-7eee527dc1a5')),
        ),
    ]
