# Generated by Django 5.1.2 on 2025-01-13 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0080_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3fb2c07-e4f6-4066-be4e-3ea88f8c7050')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3fb2c07-e4f6-4066-be4e-3ea88f8c7050')),
        ),
    ]
