# Generated by Django 5.1.5 on 2025-03-24 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0082_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a3e0db91-0d1b-46f5-8738-1abe2c68aed6')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a3e0db91-0d1b-46f5-8738-1abe2c68aed6')),
        ),
    ]
