# Generated by Django 5.1.5 on 2025-04-08 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0083_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a9d0c136-563e-4a8e-b241-42ca9be5dc79')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a9d0c136-563e-4a8e-b241-42ca9be5dc79')),
        ),
    ]
