# Generated by Django 5.1.5 on 2025-04-08 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0084_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4498d4b5-44e7-48f7-851d-8e7d99a3921e')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4498d4b5-44e7-48f7-851d-8e7d99a3921e')),
        ),
    ]
