# Generated by Django 5.1.5 on 2025-04-10 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0085_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a61bfd74-adee-4b74-b976-b32a45afe0eb')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a61bfd74-adee-4b74-b976-b32a45afe0eb')),
        ),
    ]
