# Generated by Django 5.1.5 on 2025-09-29 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0086_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('69954df4-cb8f-4c80-9978-b71ac12ce4cf')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('69954df4-cb8f-4c80-9978-b71ac12ce4cf')),
        ),
    ]
