# Generated by Django 5.1.5 on 2025-09-29 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0087_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7911f8ad-4371-4ea7-84b1-f4505920ab30')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7911f8ad-4371-4ea7-84b1-f4505920ab30')),
        ),
    ]
