# Generated by Django 5.1.5 on 2025-09-29 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0089_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4ab69f62-b774-4af3-b286-a3c2662ea1e5')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4ab69f62-b774-4af3-b286-a3c2662ea1e5')),
        ),
    ]
