# Generated by Django 5.1.5 on 2025-09-29 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0090_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('832ceead-7eb1-4664-a592-d0b678e6656f')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('832ceead-7eb1-4664-a592-d0b678e6656f')),
        ),
    ]
