# Generated by Django 5.1.5 on 2025-09-29 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0091_alter_user_uuid_alter_userevent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fa36c510-36ff-4533-b624-a9a1e978191c')),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fa36c510-36ff-4533-b624-a9a1e978191c')),
        ),
    ]
