# Generated by Django 5.1.5 on 2025-09-29 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('56744b14-9bc8-49b5-b96e-8c7e8c5f3924')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('94b6bf3f-02e7-4e85-8fd8-7617f2d191e2')),
        ),
    ]
