# Generated by Django 5.1.5 on 2025-09-29 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9c3d7977-89d6-472c-b5a8-e266719488c8')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6d58336b-dba9-4b38-a7ba-f8d1fc2603d1')),
        ),
    ]
