# Generated by Django 5.1.5 on 2025-09-29 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b661e8b9-b21b-4ad9-9b7e-1b82d9227560')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('84199528-af91-4b3d-a94f-82d06ca75073')),
        ),
    ]
