# Generated by Django 5.1.5 on 2025-09-29 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_user_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6d31a17e-b828-4ef0-ae66-e3e944089bd5')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('72fed5b1-7857-4c53-811a-d5a9dd9d3c91')),
        ),
    ]
