# Generated by Django 4.2.5 on 2023-11-30 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_uuid_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e0df9204-dff1-4783-8d20-141bb3741993')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('859c7852-0e89-4c7b-a40f-4430d36d769b')),
        ),
    ]
