# Generated by Django 4.2.5 on 2023-11-30 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('600d73c9-ece0-4572-a250-aa0dad2b9522')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('11b91072-184b-46bd-bf44-4ed7be947329')),
        ),
    ]
