# Generated by Django 4.2.5 on 2023-12-04 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c73b2cda-41c8-4a14-a168-0d1f2f5b8dd0')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5dfe9798-564e-4f68-a209-e717142d52c0')),
        ),
    ]
