# Generated by Django 4.2.5 on 2023-12-04 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6f430662-cd24-454f-8901-c14f9c7b6aaf')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9042445f-8a17-4f39-84f7-c0203971c4dc')),
        ),
    ]
