# Generated by Django 4.2.5 on 2023-12-18 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2fa36bc8-f543-4bdf-b840-c2385d6f8dfc')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2f1eb043-59a8-44ef-a8bf-28df1e00ccff')),
        ),
    ]
