# Generated by Django 4.2.5 on 2023-12-29 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_cart_uuid_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b8153248-ab46-42ab-bcc8-a8f5d8f1d642')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a53e1636-2c70-4e0c-a516-f8b1b784d108')),
        ),
    ]
