# Generated by Django 4.2.5 on 2024-01-02 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cfcff445-00a9-4f32-a482-a9026b6c8f4c')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b0c4f9d4-9624-46c7-b404-ecdf088695d9')),
        ),
    ]
