# Generated by Django 4.2.5 on 2024-03-04 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1dc11728-ef8c-464d-8ba4-942591b6dbc6')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b7010554-04de-4674-a875-678c2bd60115')),
        ),
    ]
