# Generated by Django 4.2.5 on 2024-05-23 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('972adb83-220a-4b99-98ee-8202cd37fd36')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e62a9084-0033-4209-8174-5ddb65eb515f')),
        ),
    ]
