# Generated by Django 4.2.5 on 2024-05-24 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cb95f04f-f385-4664-8a96-61ed3cc20232')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('34436227-1bf8-4f11-82a1-3b3c2a527dd9')),
        ),
    ]
