# Generated by Django 4.2.5 on 2024-05-24 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('608c9063-4d37-4752-b7de-fd6fcf904dea')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('590b65d6-3225-4ac9-99f4-8dbb937df1ed')),
        ),
    ]
