# Generated by Django 4.2.5 on 2024-05-24 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ed96a94e-8efc-43a4-a61e-eb1813b51a15')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6147197d-a6db-43d2-a5f9-44554e02f265')),
        ),
    ]
