# Generated by Django 4.2.5 on 2024-06-02 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('105da4e5-075a-4176-8bd3-615b7e5747bc')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('381d67c7-389d-4c93-8b36-b18630856f78')),
        ),
    ]
