# Generated by Django 4.2.5 on 2024-06-05 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('19ff9fb9-4db2-49fd-8370-6a1b38b89d3c')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0d6c923f-0b76-4e54-9a72-1fa8e76f31d8')),
        ),
    ]
