# Generated by Django 4.2.5 on 2024-06-05 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('60462eaf-dae0-478f-a619-07ec5f5278c9')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('373e9d52-9ed6-462d-b9ae-652d496c7599')),
        ),
    ]
