# Generated by Django 4.2.5 on 2024-07-01 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0037_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ba049d9e-5295-408e-aeb8-b2e5372b0a4d')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1ab1cdf6-c0b5-4cf3-b332-83c24985d5c2')),
        ),
    ]
