# Generated by Django 4.2.5 on 2024-07-03 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0039_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4919b4bc-6b47-439b-9150-c8135aa428fb')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('630e9f15-7124-42a3-b239-3cabe9bb59ff')),
        ),
    ]
