# Generated by Django 4.2.5 on 2024-07-03 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0040_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ff553d28-75de-4bf1-bc71-aadc6f8df5b1')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7638c416-b66b-4b05-9a2e-dbb5f2bc83c0')),
        ),
    ]
