# Generated by Django 4.2.5 on 2024-07-03 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0042_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('42fac7c4-91ec-437f-9004-73250440fcab')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('24c61b94-f810-4c7f-a25b-c0d75fd2731e')),
        ),
    ]
