# Generated by Django 4.2.5 on 2024-08-21 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0044_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6b21ba1f-efef-4ee6-aab7-932cc14ab05d')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b9f2a964-bed0-489c-b791-b94ddb80a5c1')),
        ),
    ]
