# Generated by Django 4.2.5 on 2024-08-22 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0045_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7e19b98c-3139-4f38-bcba-5df78ae1f0ec')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4531e999-0dd4-4c4a-a417-3d31d6cfa5fd')),
        ),
    ]
