# Generated by Django 4.2.5 on 2024-09-21 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0047_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9307cd5c-2e31-4d96-8b63-a7be66e32b05')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5e3496bf-4f0b-4454-9143-3416e3263e4e')),
        ),
    ]
