# Generated by Django 4.2.5 on 2024-09-21 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0049_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5f94b0d6-8b0e-4e1d-b230-734fd791a7a4')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5283490f-93b8-4a46-8fb4-409648cfbe31')),
        ),
    ]
