# Generated by Django 4.2.5 on 2024-09-21 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0050_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('681dc7dd-f922-4f56-8181-5e02dfb64a89')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9c4bc368-b07d-4a0c-953f-cd9fbac52916')),
        ),
    ]
