# Generated by Django 4.2.5 on 2024-09-21 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0051_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('08965835-e29a-44d4-9ece-c439f3acab4e')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c2e15b78-4bd8-41d6-8c6c-6650543b63a1')),
        ),
    ]
