# Generated by Django 5.1.2 on 2024-10-10 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0053_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='modification_alert',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6d3b4b0-483b-4d8b-9202-b18d1fa886ce')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='modification_alert',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e2e3612e-132c-4ae3-90a6-891f548b0b63')),
        ),
    ]
