# Generated by Django 5.1.2 on 2024-10-10 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0054_alter_cart_modification_alert_alter_cart_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('16e0d0af-fe49-4d71-9547-2e7cc531e4ac')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('122f44c3-e429-4324-a99b-4cef9b431434')),
        ),
    ]
