# Generated by Django 5.1.2 on 2024-10-10 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0055_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0576a7c1-4e89-43cd-b77a-c55c586d8675')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b469d5a6-91a8-461a-b17e-d180eb22b5e8')),
        ),
    ]
