# Generated by Django 5.1.2 on 2024-10-10 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0056_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5667042b-2bb9-49c7-9178-7986cbaa6bb0')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('66de2969-2e57-420e-8eb5-bab3d090002c')),
        ),
    ]
