# Generated by Django 5.1.2 on 2024-10-10 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0057_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2763c128-81ca-477c-9ade-a8386bef7c3a')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2c77007f-64fa-485d-87f0-b8371266c238')),
        ),
    ]
