# Generated by Django 5.1.2 on 2024-10-10 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0058_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ceca36a6-e8c0-4389-a75e-5b6a60476658')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f943b504-abf5-4780-ad80-ef682631c07d')),
        ),
    ]
