# Generated by Django 5.1.2 on 2024-10-10 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0061_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6218f281-9621-4019-9878-61df390b80f8')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8c6d1e20-cf2d-483c-8959-9eef7931c7d6')),
        ),
    ]
