# Generated by Django 5.1.2 on 2024-10-21 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0062_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c6ac1b2b-5b32-4518-aeab-c40b0b875bb8')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a0d57b6c-34ee-4933-a572-ab67bcd99e5c')),
        ),
    ]
