# Generated by Django 5.1.2 on 2024-10-22 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0064_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0b388f95-1a47-4d2a-ab6f-908c603dac77')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f3fd2efa-60c7-41d5-b93c-30f94c331f89')),
        ),
    ]
