# Generated by Django 5.1.2 on 2024-10-22 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0065_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4d30af2b-0583-4dc2-923d-12819c60d385')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a83976bd-e334-4aac-a283-29fc969ff5ed')),
        ),
    ]
