# Generated by Django 5.1.2 on 2024-10-22 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0067_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cc07acac-6f76-413f-8a18-5ed974207bf5')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8a0f7d00-da54-4689-ad81-1a60ed3dbeae')),
        ),
    ]
