# Generated by Django 5.1.2 on 2024-10-23 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0069_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('652a5413-2033-441e-aa70-f80ca8fc25a8')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('69dd7399-aea6-48c8-9015-c2c8222625aa')),
        ),
    ]
