# Generated by Django 5.1.2 on 2024-10-25 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0071_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('175335bf-2b09-46c4-8d87-cac7ee92bfc0')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ccdd1677-53c6-4303-a6de-da1067c5fb47')),
        ),
    ]
