# Generated by Django 5.1.2 on 2024-11-19 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0073_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7309e5fe-f362-4896-815c-4242f1c4a237')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bc6b0b07-fb39-4c9e-8c9b-0bf7a8c10e9e')),
        ),
    ]
