# Generated by Django 5.1.2 on 2024-12-18 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0074_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('331c76e7-b0af-4f72-a208-e3f95ad44b1c')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('78586654-a49c-4782-8373-5845f4ef3792')),
        ),
    ]
