# Generated by Django 5.1.2 on 2025-01-13 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0075_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e028e134-ed1d-4b91-8bc8-c6c75c90bcbb')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0c80dd74-646e-4a66-af9d-ba20b35550cf')),
        ),
    ]
