# Generated by Django 5.1.2 on 2025-01-13 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0076_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6581755c-0603-4fec-8340-98a57e9fb177')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ffbf337a-125e-4fd2-b471-b4a31cce161b')),
        ),
    ]
