# Generated by Django 5.1.5 on 2025-02-07 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0078_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attributes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('81b5ddad-54d8-4da9-837c-a00a16faedf3')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('292c2776-3a04-46c4-a9c8-65495b18ae74')),
        ),
    ]
