# Generated by Django 5.1.5 on 2025-04-08 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0080_alter_cart_uuid_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7db81440-b373-4c80-b6cb-b497ea90819c')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1cf3e415-92da-4784-8856-fb4da84a00b4')),
        ),
    ]
