# Generated by Django 5.1.5 on 2025-04-10 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0082_alter_cart_uuid_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('399a3375-76d7-46bb-a2eb-377a0c17668e')),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('65c48dd3-8689-4bf5-b61e-7f819509253d')),
        ),
    ]
