# Generated by Django 4.2.5 on 2023-12-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
