# Generated by Django 5.1.5 on 2025-09-29 10:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('purchase.order.draft', 'Draft'), ('purchase.order.buyer.rejected', 'Buyer Rejected'), ('purchase.order.supplier.rejected', 'Supplier Rejected'), ('purchase.order.approved', 'Approved'), ('purchase.order.shipped', 'Shipped'), ('purchase.order.received', 'Received')], max_length=40)),
                ('total_price', models.FloatField()),
                ('is_shipped', models.BooleanField(db_default=False)),
                ('date_shipped', models.DateTimeField(null=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('ba1e510e-d977-4886-925b-3df03ee977a8'))),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(default=None, max_length=120)),
                ('manufacturer', models.CharField(default=None, max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField()),
                ('uuid', models.UUIDField(default=uuid.UUID('c6d76c06-a150-480a-8de6-a90bc8d0f6c5'))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_shipped', False)), fields=['id'], name='unshipped_orders'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_shipped', False)), fields=['buyer_id'], name='order_buyer_id'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_shipped', False)), fields=['supplier_id'], name='order_supplier_id'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('is_shipped', False)), fields=('buyer_id', 'is_shipped'), name='limit_pending_orders'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('product_name', 'sku', 'manufacturer', config='english'), name='s_order_item_product_name_idx'),
        ),
    ]
