# Generated by Django 5.1.5 on 2025-09-29 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ccc6f26f-8492-4cbe-adc7-4925524f4944')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e5d2533f-5c8f-4524-915f-25ad7a0c6dfa')),
        ),
    ]
