# Generated by Django 5.1.5 on 2025-09-29 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('532706b6-424f-4975-8e5e-254d734b830d')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('226ddd02-03a9-43e1-a5f1-a3301b2dcd42')),
        ),
    ]
