# Generated by Django 5.1.5 on 2025-09-29 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f6de8aa2-0db5-49cc-994c-a938d2655382')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a322c2e5-e391-4b5a-83ac-77aab84dfe1d')),
        ),
    ]
