# Generated by Django 5.1.5 on 2026-06-12 07:15

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_buyer_alter_order_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='limit_pending_orders',
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cff291db-e039-4e33-91aa-d4af227184b8')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('716c37b0-9487-443f-baa7-9c61c56098c2')),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'purchase.order.draft')), fields=('buyer_id', 'supplier_id'), name='limit_pending_orders'),
        ),
    ]
