# Generated by Django 4.2.5 on 2023-12-04 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3c0bf95f-905e-4d80-be28-9265e028758b')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b8de5a67-44cc-4fbe-b284-8a69ea2590bc')),
        ),
    ]
