# Generated by Django 4.2.5 on 2023-12-04 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_comments_alter_order_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('765aba01-c536-4398-a54a-c2b2ea385f93')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7b1d4cf8-fe5a-4e9e-ab02-87d45b780e3b')),
        ),
    ]
