# Generated by Django 4.2.5 on 2023-12-18 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('06fc4186-0013-46f7-89fb-d71e93966e1e')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('86dd59ab-200f-4781-9a14-63a8257348c0')),
        ),
    ]
