# Generated by Django 4.2.5 on 2023-12-18 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_uuid_alter_orderitem_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('91370b53-c893-418c-8e2b-8c5ed32793f2')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a4ebc054-7fe1-4130-9d1e-c253da922237')),
        ),
    ]
