# Generated by Django 4.2.5 on 2024-01-02 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a727810e-8f94-4e71-9d02-e1b4fce586a6')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4adcbc3c-fb28-4d08-83ca-b76200ee6c74')),
        ),
    ]
