# Generated by Django 4.2.5 on 2024-05-23 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5fec68bc-2da5-46a5-ad9f-3b9df3798787')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4dd09d20-868e-4c1b-9658-10bd36e8a76c')),
        ),
    ]
