# Generated by Django 4.2.5 on 2024-05-24 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c045a16b-2288-4f6e-a61e-bae3a04b6f8c')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0289a5f6-3d8a-4621-b4a5-41604aa23326')),
        ),
    ]
