# Generated by Django 4.2.5 on 2024-05-24 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ed1cf7b6-ee9a-4394-b857-970d21175875')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b8326af3-0abf-4b29-b9b0-02b8bc2d6544')),
        ),
    ]
