# Generated by Django 4.2.5 on 2024-06-01 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f4f44335-c417-404e-ac8f-110371d7eb8d')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('da850c01-a8f1-470e-bfa0-83d0a62bed91')),
        ),
    ]
