# Generated by Django 4.2.5 on 2024-06-05 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9c426c6e-8ded-4af7-bb23-30007bcd7b98')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('daa5fb9a-6bcf-4cf2-9700-b11306f74f0b')),
        ),
    ]
