# Generated by Django 4.2.5 on 2024-06-05 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a4429c2f-4248-4d1d-95dd-300274d4e2b5')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7f5c8c84-882b-44d8-8660-72005e84d987')),
        ),
    ]
