# Generated by Django 4.2.5 on 2024-06-05 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b7510503-d01d-42cf-99d0-8a8602fd625c')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aa949200-d673-4b1e-a63c-5c26dc2e8729')),
        ),
    ]
