# Generated by Django 4.2.5 on 2024-06-05 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b9994c69-5aae-4e4c-8b7a-baaa96c97fd3')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5eff243c-e1c5-4cec-a1d4-19197ec9adee')),
        ),
    ]
