# Generated by Django 4.2.5 on 2024-06-28 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d9ec7196-281e-4004-88ea-082396449580')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e0a5e653-d5c4-4860-afbc-b35a5d78ee18')),
        ),
    ]
