# Generated by Django 4.2.5 on 2024-07-01 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3398ca33-c48c-474b-a3eb-a155ed7afc34')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('32255ba2-3337-4ff0-a740-58c4f9eaffb6')),
        ),
    ]
