# Generated by Django 4.2.5 on 2024-07-03 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a2114bca-e8d1-44ea-bb2b-de8b1d1d1049')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9ab8923c-8a59-4907-a47e-8991a5af0abd')),
        ),
    ]
