# Generated by Django 4.2.5 on 2024-07-03 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5d35afb2-cb2f-4934-8901-98d221d0483e')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('72cbf62c-d508-4700-8043-fb60a9dfb829')),
        ),
    ]
