# Generated by Django 4.2.5 on 2024-07-03 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3b38b876-f2ca-489d-b117-cc9bd7d072dc')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c5188696-8143-4af7-acce-0afa1c381c57')),
        ),
    ]
