# Generated by Django 4.2.5 on 2024-08-21 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('39c1f209-7cde-4135-94f3-98c1c3e0725a')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('86479cc4-8cc3-4968-92c0-661a384d0e16')),
        ),
    ]
