# Generated by Django 4.2.5 on 2024-09-21 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6da73dea-9b17-44f7-9ca8-221a1085f5b8')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6c391974-a3b3-42bc-8294-dd2b5e7846ac')),
        ),
    ]
