# Generated by Django 4.2.5 on 2024-09-21 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8aa42b9b-4c3d-4814-a6a5-4fd5d35a77e8')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('94f83b46-94b1-49a7-9574-91a32c26bb33')),
        ),
    ]
