# Generated by Django 5.1.2 on 2024-10-10 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('67b5968e-9db6-4b56-9da4-d17db14725d5')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e13afa30-ec6e-4ef0-b731-9f20184629b8')),
        ),
    ]
