# Generated by Django 5.1.2 on 2024-10-10 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aaf32a21-1a38-492a-ab3d-9ee1ddf556d3')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dddfb62b-6b36-467d-b1a9-03887ad779ba')),
        ),
    ]
