# Generated by Django 5.1.2 on 2024-10-10 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bc20fbdc-c4e8-43b2-8266-c077de8dba34')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('188c9ffe-a4e2-461b-9b53-9c9401ee2f3f')),
        ),
    ]
