# Generated by Django 5.1.2 on 2024-10-10 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2dadd156-34cc-4d65-8988-ea66af821f80')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1b5256b6-b992-44c4-b7e7-9a390948df8c')),
        ),
    ]
