# Generated by Django 5.1.2 on 2024-10-21 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('033a27f7-4850-4e3c-a0a4-897bd04db1b0')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6a530237-38d2-4759-b45d-d95e76e217b9')),
        ),
    ]
