# Generated by Django 5.1.2 on 2024-10-22 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('41f85e01-f776-4c6c-bf9d-3bcf5e3ded28')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('650e1a46-a7c9-4464-9973-a6945073f01f')),
        ),
    ]
