# Generated by Django 5.1.2 on 2024-10-22 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('772606b5-6a13-497a-b974-e973d02edd96')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2d0bd5cc-0bba-4fe0-8d74-b752c47a5b68')),
        ),
    ]
