# Generated by Django 5.1.2 on 2024-10-22 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('03af6155-b2e6-4a43-a003-31cddd9694e1')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('43e567d7-3e4b-4b56-b922-a98ff7a798c4')),
        ),
    ]
