# Generated by Django 5.1.2 on 2024-10-23 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8a509453-a76b-4964-928c-945e690cad62')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f4a6f50a-a06c-419a-821e-7b8dac349a21')),
        ),
    ]
