# Generated by Django 5.1.2 on 2024-10-23 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('52675943-8f41-4c7f-b876-27f8649e4919')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3d09c72-58c0-411e-96f0-d24f067a852d')),
        ),
    ]
