# Generated by Django 5.1.2 on 2024-10-24 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1cb53fbd-802f-4198-88a7-0eadc6c00e8d')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bf78dae8-8c23-44b7-a7fe-67ddcbf94297')),
        ),
    ]
