# Generated by Django 5.1.2 on 2024-10-25 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0066_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('869f0a10-9af0-4e8b-afa9-09f7e3afb5eb')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4056df08-3607-41ac-8656-8486dddfff48')),
        ),
    ]
