# Generated by Django 5.1.2 on 2024-12-18 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a0b12265-c5b6-45c1-b496-c2a0242f156c')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('15082010-b873-4670-9c61-cfd6ebc19fbe')),
        ),
    ]
