# Generated by Django 5.1.2 on 2025-01-13 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e953450-f0de-43e7-b3ea-8c6f6987c310')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('22eda4de-98e8-49eb-8183-68d29766c0b0')),
        ),
    ]
