# Generated by Django 5.1.2 on 2025-01-13 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('17da59d3-c043-48da-b4ac-5b7ffeab76c6')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('21132ab6-8d8d-478c-a034-6db2a8022568')),
        ),
    ]
