# Generated by Django 5.1.2 on 2025-01-13 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0072_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3692f50c-833d-4eb7-b1ea-a753340ea4da')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ec073a5a-b9c0-4f51-b9e2-3a478b7a1328')),
        ),
    ]
