# Generated by Django 5.1.5 on 2025-04-08 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1a687200-4ecf-443a-a252-243e61f46642')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('32536042-cfa4-4e1e-a991-0e08c0d3618d')),
        ),
    ]
