# Generated by Django 5.1.5 on 2025-04-08 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aee3cd10-da59-4931-a3f1-5dec1c22c071')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c2525d19-bcea-46d8-a593-2e29e35bafdd')),
        ),
    ]
