# Generated by Django 5.1.5 on 2025-04-10 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0077_alter_order_uuid_alter_orderitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ecfa422b-54b0-46f4-98c0-492f4f360a03')),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('55a73102-9021-4abf-89b8-3378b92c4e08')),
        ),
    ]
