# Generated by Django 4.2.5 on 2023-10-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Seller'), (1, 'Customer')], primary_key=True, serialize=False),
        ),
    ]
