# Generated by Django 4.2.5 on 2023-10-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
