# Generated by Django 4.2.5 on 2023-10-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
