# Generated by Django 4.2.5 on 2023-11-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_remove_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
