# Generated by Django 4.2.5 on 2023-11-30 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('de52add7-ce36-440f-b15d-aad9186ac759')),
        ),
    ]
