# Generated by Django 4.2.5 on 2023-12-04 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0015_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e50e0939-d977-4630-bfff-d185e594506d')),
        ),
    ]
