# Generated by Django 4.2.5 on 2023-12-18 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('596bc1ab-1b7e-428e-a52e-c31376eb1de6')),
        ),
    ]
