# Generated by Django 4.2.5 on 2023-12-18 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0018_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8ce9a467-347c-4847-8f2e-00d2ee36df43')),
        ),
    ]
