# Generated by Django 4.2.5 on 2023-12-29 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0020_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('23c1fad2-46f7-4b1a-ad1e-d608d9ee19d1')),
        ),
    ]
