# Generated by Django 4.2.5 on 2024-01-02 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0022_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('39d417b9-9d41-45f4-9c2c-f471edf0c560')),
        ),
    ]
