# Generated by Django 5.1.5 on 2026-06-12 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('purchase.order.created', 'Order Created'), ('purchase.order.buyer.rejected', 'Buyer Rejected'), ('purchase.order.supplier.rejected', 'Supplier Rejected'), ('purchase.order.approved', 'Approved'), ('purchase.order.shipped', 'Shipped'), ('purchase.order.received', 'Received')], max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('notification.status.created', 'Created'), ('notification.status.sent', 'Sent'), ('notification.status.failed', 'Failed')], default='notification.status.created', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notification_unread_idx')],
            },
        ),
    ]
