# Generated by Django 5.1.5 on 2025-09-29 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f814cbb9-7e81-49ef-bd66-9cefc9dabab6')),
        ),
    ]
