# Generated by Django 5.1.5 on 2025-09-29 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_uuid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_user_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('875f5dda-b7ed-4fd3-bed5-ab5a26add419')),
        ),
    ]
