# Generated by Django 4.2.5 on 2023-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku']},
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
