# Generated by Django 5.1.5 on 2025-09-29 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_product_user_id_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('eb721bb6-3334-4b21-bb80-20c552cb2810')),
        ),
    ]
