# Generated by Django 4.2.5 on 2023-11-30 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4578868a-a788-4cf3-935c-a1a7493469f4')),
        ),
    ]
