# Generated by Django 4.2.5 on 2023-12-04 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('283dc0c4-51b8-4896-93c9-239e68115e0b')),
        ),
    ]
