# Generated by Django 4.2.5 on 2023-12-18 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8705e90d-4baf-4572-af12-6953b61a420a')),
        ),
    ]
