# Generated by Django 4.2.5 on 2023-12-18 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b3c44912-0fbb-4d34-84dd-ef3abb8c7634')),
        ),
    ]
