# Generated by Django 4.2.5 on 2023-12-29 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('71c09302-431b-49af-bd8e-3a791e1c3273')),
        ),
    ]
