# Generated by Django 4.2.5 on 2024-01-02 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('597a7633-1c13-47c0-aaf5-a4f66e93c7a1')),
        ),
    ]
