# Generated by Django 4.2.5 on 2024-01-02 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1abd0c01-9ca2-47cc-b160-fd12038744d2')),
        ),
    ]
