# Generated by Django 4.2.5 on 2024-03-04 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3c78bf4-6d5f-4a06-b278-8687044bbf76')),
        ),
    ]
