# Generated by Django 4.2.5 on 2024-05-23 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4453094c-5791-4822-9f94-73dc379cf9cc')),
        ),
    ]
