# Generated by Django 4.2.5 on 2024-05-23 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('afc0e4a1-c277-42a3-ba0a-10d6577b554e')),
        ),
    ]
