# Generated by Django 4.2.5 on 2024-05-23 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8dbeaeb6-0187-4b9e-b33c-79852d0866bf')),
        ),
    ]
