# Generated by Django 4.2.5 on 2024-05-24 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('315c3eef-b7af-4964-ad33-fd0834515baf')),
        ),
    ]
