# Generated by Django 4.2.5 on 2024-05-24 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6c6c6362-1af5-4759-a056-17ef68e09f08')),
        ),
    ]
