# Generated by Django 4.2.5 on 2024-05-24 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7653649e-9f2f-4cf2-acb7-edb9543b0eb8')),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['uuid'], name='product_uuid'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user_id'], name='product_user_id'),
        ),
    ]
