# Generated by Django 4.2.5 on 2024-05-24 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_uuid_product_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ac16e542-b2b2-43b3-811e-cac6cc2bcb6a')),
        ),
    ]
