# Generated by Django 4.2.5 on 2024-06-01 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aee2c742-751b-43a0-9c41-99a040c5d233')),
        ),
    ]
