# Generated by Django 4.2.5 on 2024-06-05 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('36241ecd-be9b-496e-94a7-275ecce0eeaf')),
        ),
    ]
