# Generated by Django 4.2.5 on 2024-06-05 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bc681680-e25e-420b-8b26-a7eeb5460377')),
        ),
    ]
