# Generated by Django 4.2.5 on 2024-06-05 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f27fdf42-c9ff-48ea-95e0-c7d803c92041')),
        ),
    ]
