# Generated by Django 4.2.5 on 2024-07-01 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_attribute_brand_category_product_number_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d053366-a4a9-436d-9d03-2d55911549dd')),
        ),
    ]
