# Generated by Django 4.2.5 on 2024-07-03 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3b712481-6e72-4abe-8bcc-1687d8f402a0')),
        ),
    ]
