# Generated by Django 4.2.5 on 2024-07-03 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('01a347e7-208e-4d12-a198-d23c1e57afe2')),
        ),
    ]
