# Generated by Django 4.2.5 on 2024-08-21 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('face5302-4342-4b37-8b42-b75832080a75')),
        ),
    ]
