# Generated by Django 4.2.5 on 2024-08-22 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3fc4b1c8-4220-40e8-b962-e11b79b42c0a')),
        ),
    ]
