# Generated by Django 4.2.5 on 2024-09-21 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5f9c60c3-b570-4b1a-bf7d-cddd499d6975')),
        ),
    ]
