# Generated by Django 4.2.5 on 2024-09-21 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d2e5e082-0386-47cf-a7c1-e833d2f594fe')),
        ),
    ]
