# Generated by Django 4.2.5 on 2024-09-21 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('32175b54-0f0c-44f0-be18-94e74362a9e4')),
        ),
    ]
