# Generated by Django 4.2.5 on 2024-09-21 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3167d48-ab02-415d-9282-103d3cc2c281')),
        ),
    ]
