# Generated by Django 4.2.5 on 2024-09-21 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('596eb910-93a5-4157-89a1-8105df5a929e')),
        ),
    ]
