# Generated by Django 5.1.2 on 2024-10-10 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='public',
            field=models.BooleanField(db_default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b331657e-dcb7-44a3-9225-3cd58ec4eb12')),
        ),
    ]
