# Generated by Django 5.1.2 on 2024-10-10 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_product_search_alter_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(db_default=1, on_delete=django.db.models.deletion.PROTECT, to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(db_default=1, to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('feb975ec-98e8-40c1-8cb3-26e39a1c0121')),
        ),
    ]
