# Generated by Django 5.1.2 on 2024-10-10 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_product_brand_product_category_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('821b594c-7f48-41ce-883a-2a04610f3206')),
        ),
        migrations.CreateModel(
            name='AttributeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(default=None, max_length=120)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_options', to='products.attribute')),
            ],
        ),
    ]
