# Generated by Django 5.1.2 on 2024-10-10 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_alter_attribute_type_alter_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('product.availability.in.stock', 'In Stock'), ('product.availability.out.of.stock', 'Out Of Stock')], db_default='product.availability.in.stock', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('product.status.published', 'Published'), ('product.status.scheduled', 'Scheduled')], db_default='product.status.published', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fee1be25-0d43-49e6-a005-7b54d5db3f13')),
        ),
    ]
