# Generated by Django 5.1.2 on 2024-10-21 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_product_availability_status_product_publish_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search',
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a746a1d0-d420-422c-bced-ab8333ef6197')),
        ),
    ]
