# Generated by Django 5.1.2 on 2024-10-22 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_product_search_alter_product_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search',
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b211aafd-0332-403b-b9ef-d8520a46fb95')),
        ),
    ]
