# Generated by Django 5.1.2 on 2024-10-22 04:23

import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_remove_product_search_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('sku', 'title', 'content', 'fabric_details', 'care_instructions', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('17ed5297-87b5-4267-b8e9-374a71d1f27f')),
        ),
    ]
