# Generated by Django 5.1.2 on 2024-10-22 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_alter_attributeoptions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e5e109db-d90d-4a37-80b3-288dac51e868')),
        ),
        migrations.AlterModelTable(
            name='attributeoptions',
            table='products_attribute_options',
        ),
        migrations.AlterModelTable(
            name='productattributevalues',
            table='products_attribute_values',
        ),
    ]
