# Generated by Django 5.1.2 on 2024-10-23 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_alter_product_uuid_alter_attributeoptions_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('541dce47-f4e7-4494-9569-d11dd38e885f')),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='attribute_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='attribute_value_method',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
