# Generated by Django 5.1.2 on 2024-10-25 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_discount_alter_product_uuid_productsdiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsdiscount',
            options={'verbose_name_plural': 'Products Discounts'},
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('162d3a0d-43f2-4fd9-855e-0daac5d40589')),
        ),
        migrations.AlterModelTable(
            name='productsdiscount',
            table='products_product_discount',
        ),
    ]
