# Generated by Django 5.1.2 on 2024-10-30 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_alter_productsdiscount_options_alter_product_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='promo_end',
            new_name='discount_end',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='promo_start',
            new_name='discount_start',
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3c5f4748-a67b-40b4-8d7d-9f6006581964')),
        ),
    ]
