# Generated by Django 5.1.2 on 2025-01-13 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_product_average_rating_product_number_of_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(db_default=1, related_name='product', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('10bea98d-d408-49c2-9c66-2b93bc81e368')),
        ),
    ]
