# Generated by Django 5.1.2 on 2025-01-13 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_alter_product_category_alter_product_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ca56775b-8f77-4aad-be37-9d42274205cd')),
        ),
    ]
