# Generated by Django 5.1.5 on 2025-02-07 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0077_alter_product_categories_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a522f684-5137-44e6-9d98-727ccc9676c3')),
        ),
    ]
