# Generated by Django 5.1.5 on 2025-03-24 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('60305f09-3233-4da8-a5fc-8965d4579dc9')),
        ),
    ]
