# Generated by Django 5.1.5 on 2025-04-08 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0079_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e110930b-c634-4a34-a229-a23a43d1c531')),
        ),
    ]
