# Generated by Django 5.1.5 on 2025-04-08 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('72bc6b5c-f132-4f99-9752-75adbf0855c4')),
        ),
    ]
