# Generated by Django 5.1.5 on 2025-04-10 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('99a7b058-ee23-4dec-b4ce-73dd02cd533e')),
        ),
    ]
